### ISSUE TITLE
The dependency graph could not be satisfied

### ISSUE THREAD

**Issue by Antonasg** [vapor-community/mongo-driver#1]
I can't build with SPM with version `0.1.0` and version `0.7` of Fluent.
I get the `The dependency graph could not be satisfied` error from SPM.
There must be some dependency somewhere that requires different versions of the same dependency, but I'm not sure. I also have the same problem using the mysql-driver.

**Comment by tanner0101** [comment]
You can check to see which version of Fluent this is compatible with in its Package.swift. We are working on updating the repos as quickly as we can.
