### ISSUE TITLE
Support unions / aggregations

### ISSUE THREAD

**Issue by tanner0101** [vapor-community/mongo-driver#13]
Unions are currently unsupported making `siblings` relations impossible in Fluent.
- https://docs.mongodb.com/manual/aggregation/
- https://github.com/OpenKitten/MongoKitten/blob/8a14994d2da03b6db841225ca34e3701af2b74fb/Sources/MongoKitten/Collection.swift#L966

Would need to go here:

https://github.com/vapor/mongo-driver/blob/master/Sources/Query%2BMongoKitten.swift#L12

Something like:

``` swift
if query.unions.count > 0 {
    // do mongo magic
}
```

**Comment by tanner0101** [comment]
Also putting a nicer error for: https://github.com/vapor/mongo-driver/blob/master/Sources/Filter%2BMongoKitten.swift#L55 would be nice.

**Comment by Joannis** [comment]
@tannernelson this can be solved another way too.
So if you store the ObjectId (or other ID that you're using) in the Document of the model and your model knows what collection you're referencing to. Let's say the `PrivateMessage` object referencing to `User` object. This Model (privatemessage) knows that it's referencing a User model, thus it can be resolved that way. It costs an extra query. Alternatively you can store a https://docs.mongodb.com/manual/reference/database-references/#dbrefs and resolve that automatically. I've already added support for DBRefs in the upcoming MongoKitten, [but it's not difficult at all to implement](https://github.com/OpenKitten/MongoKitten/blob/mongokitten2/Sources/MongoKitten/DBRef.swift)

**Comment by tanner0101** [comment]
```
{
   $lookup:
     {
       from: <collection to join>,
       localField: <field from the input documents>,
       foreignField: <field from the documents of the "from" collection>,
       as: <output array field>
     }
}
```

Looks like this is how to do it.

http://stackoverflow.com/questions/2350495/how-do-i-perform-the-sql-join-equivalent-in-mongodb

```swift
let pipeline: AggregationPipeline = [
	.lookup(fromCollection: String, localField: String, foreignField: String, as: String)
]
```

**Comment by Joannis** [comment]
Yup. It's already supported in MongoKitten. Please note that this is a feature requiring MongoDB 3.2 or above. MongoKitten will throw an error if this is used on lower versions.
