### ISSUE TITLE
CryptoEssentials Package.swif error

### ISSUE THREAD

**Issue by erickva** [vapor-community/mongo-driver#3]
When I add the mongo-driver git to my app's package and try to execute `swift build` I get the following error:
`./Packages/CryptoEssentials.git/Package.swift:5:23: error: argument 'dependencies' must precede argument 'exclude'`

**Comment by tanner0101** [comment]
0.2.0 hadn't been tagged yet: https://github.com/vapor/mongo-driver/releases/tag/0.2.0

Try that out.
